### ISSUE TITLE
Building at Windows

### ISSUE THREAD

**Issue by ismailhkose** [davidstutz/googlemock-example#1]
Have you tried your instructions to build on Windows? It doesn't generate Makefile on Windows.

$ cmake -DBUILD_GMOCK=On ../
-- Building for: Visual Studio 15 2017
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: D:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/gcc.exe
-- Check for working C compiler: D:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/c++.exe
-- Check for working CXX compiler: D:/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-rev0/mingw64/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: C:/Users/ismail/Anaconda3/python.exe (found version "3.6.5")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/test/googlemock-example/build

When I use the following commang to generate Makegile on MinGW, I see the following issues. Any idea?

$ cmake -G "Unix Makefiles" .. -DBUILD_GMOCK=On
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by davidstutz** [comment]
Personally, I never used CMake on Windows with MinGW. But it seems that Windows' CMake just works differently - if CMAKE_C_COMPILER is not set, CMake is probably not able to identify your C compiler.
